spring:
  data:
    mongodb:
      uri: mongodb://mongodb/SURL
  redis:
    host: redis
    port: 6379
    time-to-live: 600000
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true